name = "Regrid1D"
uuid = "6f747380-20fb-43ad-8521-36db71e92b2d"
authors = ["Johannes Fried <jcmf.schule@gmail.com> and contributors"]
version = "0.1.0"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
SpecialFunctions = "2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
